- id: '1597192388375'
  name: All Lights Off
  entities:
    light.my_bedroom_main_lights:
      device_id: '11'
      zone_id: '7'
      friendly_name: Bedroom Light
      icon: mdi:dome-light
      supported_features: 33
      state: 'off'
    light.office_main_lights:
      device_id: '9'
      zone_id: '5'
      friendly_name: Main Office Light
      icon: mdi:dome-light
      supported_features: 33
      state: 'off'
    light.the_bathroom_main_lights:
      device_id: '10'
      zone_id: '6'
      friendly_name: Bathroom LIght
      icon: mdi:dome-light
      supported_features: 33
      state: 'off'
    switch.reading_lamp:
      friendly_name: Reading Lamp
      state: 'on'
    switch.living_room_lamp:
      friendly_name: Living Room Lamp
      icon: mdi:power-plug
      state: 'off'
    light.hallway_light:
      friendly_name: Hallway Light
      icon: mdi:dome-light
      supported_features: 1
      state: 'off'
    light.cupboard_leds:
      effect_list:
      - blue_fade
      - blue_strobe
      - colorjump
      - colorloop
      - colorstrobe
      - cyan_fade
      - cyan_strobe
      - gb_cross_fade
      - green_fade
      - green_strobe
      - purple_fade
      - purple_strobe
      - rb_cross_fade
      - red_fade
      - red_strobe
      - rg_cross_fade
      - white_fade
      - white_strobe
      - yellow_fade
      - yellow_strobe
      - random
      friendly_name: Cupboard LEDs
      supported_features: 21
      state: 'off'
  icon: mdi:lightbulb-off
- id: '1597192557396'
  name: All Lights On
  entities:
    light.my_bedroom_main_lights:
      brightness: 255
      device_id: '11'
      zone_id: '7'
      friendly_name: Bedroom Light
      icon: mdi:dome-light
      supported_features: 33
      state: 'on'
    light.office_main_lights:
      brightness: 255
      device_id: '9'
      zone_id: '5'
      friendly_name: Main Office Light
      icon: mdi:dome-light
      supported_features: 33
      state: 'on'
    light.the_bathroom_main_lights:
      brightness: 255
      device_id: '10'
      zone_id: '6'
      friendly_name: Bathroom LIght
      icon: mdi:dome-light
      supported_features: 33
      state: 'on'
    switch.reading_lamp:
      friendly_name: Reading Lamp
      state: 'on'
    light.kitchen_light:
      brightness: 255
      friendly_name: Kitchen Ceiling Light
      icon: mdi:dome-light
      supported_features: 1
      state: 'on'
    switch.living_room_lamp:
      friendly_name: Living Room Lamp
      icon: mdi:power-plug
      state: 'on'
    light.cupboard_leds:
      effect_list:
      - blue_fade
      - blue_strobe
      - colorjump
      - colorloop
      - colorstrobe
      - cyan_fade
      - cyan_strobe
      - gb_cross_fade
      - green_fade
      - green_strobe
      - purple_fade
      - purple_strobe
      - rb_cross_fade
      - red_fade
      - red_strobe
      - rg_cross_fade
      - white_fade
      - white_strobe
      - yellow_fade
      - yellow_strobe
      - random
      brightness: 255
      hs_color:
      - 0
      - 0
      rgb_color:
      - 255
      - 255
      - 255
      xy_color:
      - 0.323
      - 0.329
      friendly_name: Cupboard LEDs
      supported_features: 21
      state: 'on'
    light.dining_room_chandelier:
      brightness: 255
      device_id: '8'
      zone_id: '4'
      friendly_name: Dining Room Chandelier
      icon: mdi:globe-light
      supported_features: 33
      state: 'on'
    light.hallway_light:
      brightness: 255
      friendly_name: Hallway Light
      icon: mdi:dome-light
      supported_features: 1
      state: 'on'
  icon: mdi:lightbulb-on
- id: '1605736404646'
  name: Emma Bedtime
  entities:
    light.dining_room_chandelier:
      device_id: '8'
      zone_id: '4'
      friendly_name: Dining Room Chandelier
      icon: mdi:globe-light
      supported_features: 33
      state: 'off'
    light.kitchen_light:
      friendly_name: Kitchen Ceiling Light
      icon: mdi:dome-light
      supported_features: 1
      state: 'off'
    light.hallway_light:
      friendly_name: Hallway Light
      icon: mdi:dome-light
      supported_features: 1
      state: 'off'
    switch.living_room_lamp:
      friendly_name: Living Room Lamp
      icon: mdi:power-plug
      state: 'off'
    light.my_bedroom_main_lights:
      brightness: 2
      device_id: '11'
      zone_id: '7'
      friendly_name: Bedroom Light
      icon: mdi:dome-light
      supported_features: 33
      state: 'on'
    light.the_bathroom_main_lights:
      device_id: '10'
      zone_id: '6'
      friendly_name: Bathroom LIght
      icon: mdi:dome-light
      supported_features: 33
      state: 'off'
    light.office_main_lights:
      device_id: '9'
      zone_id: '5'
      friendly_name: Main Office Light
      icon: mdi:dome-light
      supported_features: 33
      state: 'off'
    switch.reading_lamp:
      friendly_name: Reading Lamp
      state: 'off'
    light.cupboard_leds:
      effect_list:
      - blue_fade
      - blue_strobe
      - colorjump
      - colorloop
      - colorstrobe
      - cyan_fade
      - cyan_strobe
      - gb_cross_fade
      - green_fade
      - green_strobe
      - purple_fade
      - purple_strobe
      - rb_cross_fade
      - red_fade
      - red_strobe
      - rg_cross_fade
      - white_fade
      - white_strobe
      - yellow_fade
      - yellow_strobe
      - random
      friendly_name: Cupboard LEDs
      supported_features: 21
      state: 'off'
  icon: mdi:weather-night
