# Tuya / Smart Life
tuya_email: <username>
tuya_password: <password>

# Z-Wave
zwave_key: <network key for z-wave network>

# Google Assistant
google_proj_id: <gcs-project-id>
google_secure_pin: <pin-code>

# Fuel Logger
fuel_logger_username: <username>
fuel_logger_password: <password>

# sharkIQ workaround - sanitized
shark_shell_command: "/usr/bin/curl -X 'POST' -H 'authorization: Bearer <token>' http://localhost:8123/api/config/config_entries/entry/<id>/reload"
